using System.Collections.ObjectModel;
using System.Text;

namespace Yoake.Core.Subtitles;

public sealed class AssDocument
{
    internal sealed record SourceLine(string Raw, string Ending, AssRecord? Record = null);
    internal List<SourceLine> Source = [];
    private Encoding _encoding = new UTF8Encoding(false, true);
    private bool _bom;
    private string _newline = "\r\n";
    private string? _cached;
    private readonly ObservableCollection<AssEvent> _events = [];
    private readonly ObservableCollection<AssStyle> _styles = [];
    public ReadOnlyObservableCollection<AssEvent> Events { get; }
    public ReadOnlyObservableCollection<AssStyle> Styles { get; }
    public event EventHandler? Changed;
    public long Revision { get; private set; }
    public static readonly string[] EventFormat = "Layer,Start,End,Style,Name,MarginL,MarginR,MarginV,Effect,Text".Split(',');
    public static readonly string[] StyleFormat = "Name,Fontname,Fontsize,PrimaryColour,SecondaryColour,OutlineColour,BackColour,Bold,Italic,Underline,StrikeOut,ScaleX,ScaleY,Spacing,Angle,BorderStyle,Outline,Shadow,Alignment,MarginL,MarginR,MarginV,Encoding".Split(',');
    private AssDocument() { Events = new(_events); Styles = new(_styles); }
    public static AssDocument CreateEmpty() => Parse("[Script Info]\r\n; Script generated by Yoake\r\nScriptType: v4.00+\r\nPlayResX: 1920\r\nPlayResY: 1080\r\n\r\n[V4+ Styles]\r\nFormat: " + string.Join(", ", StyleFormat) + "\r\nStyle: Default,Arial,60,&H00FFFFFF,&H0000FFFF,&H00000000,&H64000000,0,0,0,0,100,100,0,0,1,2,0,2,30,30,30,1\r\n\r\n[Events]\r\nFormat: " + string.Join(", ", EventFormat) + "\r\n");
    public static AssDocument Parse(string text)
    {
        ArgumentNullException.ThrowIfNull(text);
        var doc = new AssDocument(); var section = ""; string[]? format = null;
        for (var start = 0; start < text.Length;)
        {
            var end = start; while (end < text.Length && text[end] is not '\r' and not '\n') end++;
            var after = end;
            if (after < text.Length && text[after++] == '\r' && after < text.Length && text[after] == '\n') after++;
            var raw = text[start..end]; var ending = text[end..after]; var trim = raw.Trim();
            if (doc.Source.Count == 0 && ending.Length > 0) doc._newline = ending;
            AssRecord? record = null;
            if (trim.StartsWith('[') && trim.EndsWith(']')) { section = trim; format = null; }
            else if (trim.StartsWith("Format:", StringComparison.OrdinalIgnoreCase)) format = trim[7..].Split(',').Select(s => s.Trim()).ToArray();
            else if (format is { Length: > 0 })
            {
                var colon = raw.IndexOf(':');
                if (colon > 0)
                {
                    var kind = raw[..colon].Trim(); var payload = colon + 1;
                    while (payload < raw.Length && char.IsWhiteSpace(raw[payload])) payload++;
                    if (section.Equals("[Events]", StringComparison.OrdinalIgnoreCase) && (kind.Equals("Dialogue", StringComparison.OrdinalIgnoreCase) || kind.Equals("Comment", StringComparison.OrdinalIgnoreCase)))
                        record = new AssEvent(raw[..payload], format, SplitFields(raw[payload..], format, true));
                    else if (section.Equals("[V4+ Styles]", StringComparison.OrdinalIgnoreCase) && kind.Equals("Style", StringComparison.OrdinalIgnoreCase))
                        record = new AssStyle(raw[..payload], format, SplitFields(raw[payload..], format, false));
                }
            }
            doc.Source.Add(new(raw, ending, record)); start = after;
        }
        doc.Synchronize(); return doc;
    }
    // Fields after Text are consumed from the right; commas belong to Text.
    private static string[] SplitFields(string payload, string[] format, bool events)
    {
        var text = events ? Array.FindIndex(format, f => f.Equals("Text", StringComparison.OrdinalIgnoreCase)) : -1;
        if (text < 0) return payload.Split(',', format.Length);
        var result = new string[format.Length]; var left = 0; var right = payload.Length;
        for (var i = 0; i < text; i++) { var comma = payload.IndexOf(',', left); if (comma < 0) return payload.Split(','); result[i] = payload[left..comma]; left = comma + 1; }
        for (var i = format.Length - 1; i > text; i--) { var comma = right > left ? payload.LastIndexOf(',', right - 1, right - left) : -1; if (comma < 0) return payload.Split(','); result[i] = payload[(comma + 1)..right]; right = comma; }
        result[text] = payload[left..right]; return result;
    }
    public string Serialize()
    {
        if (_cached is not null) return _cached;
        var output = new StringBuilder(); string[]? format = null;
        foreach (var line in Source)
        {
            var trim = line.Raw.Trim(); if (trim.StartsWith('[')) format = null;
            if (trim.StartsWith("Format:", StringComparison.OrdinalIgnoreCase)) format = trim[7..].Split(',').Select(s => s.Trim()).ToArray();
            if (line.Record is { } record)
            {
                if (format is null || !format.SequenceEqual(record.Format, StringComparer.OrdinalIgnoreCase)) { output.Append("Format: ").AppendJoin(", ", record.Format).Append(_newline); format = record.Format; }
                output.Append(record.Serialize());
            }
            else output.Append(line.Raw);
            output.Append(line.Ending);
        }
        return _cached = output.ToString();
    }
    public static AssDocument Load(string path)
    {
        var bytes = File.ReadAllBytes(path); Encoding encoding; var skip = 0;
        if (bytes.AsSpan().StartsWith(new byte[] { 0xEF, 0xBB, 0xBF })) { encoding = new UTF8Encoding(true, true); skip = 3; }
        else if (bytes.AsSpan().StartsWith(new byte[] { 0xFF, 0xFE })) { encoding = new UnicodeEncoding(false, true, true); skip = 2; }
        else if (bytes.AsSpan().StartsWith(new byte[] { 0xFE, 0xFF })) { encoding = new UnicodeEncoding(true, true, true); skip = 2; }
        else encoding = new UTF8Encoding(false, true);
        try { var doc = Parse(encoding.GetString(bytes, skip, bytes.Length - skip)); doc._encoding = encoding; doc._bom = skip > 0; return doc; }
        catch (DecoderFallbackException e) { throw new InvalidDataException("Unsupported legacy encoding. Convert the file to UTF-8 before opening; the original file has not been changed.", e); }
    }
    public void Save(string path)
    {
        var full = Path.GetFullPath(path); var temp = full + "." + Guid.NewGuid().ToString("N") + ".tmp";
        try { using (var stream = new FileStream(temp, FileMode.CreateNew, FileAccess.Write, FileShare.None)) { if (_bom) stream.Write(_encoding.GetPreamble()); stream.Write(_encoding.GetBytes(Serialize())); stream.Flush(true); } File.Move(temp, full, true); }
        finally { if (File.Exists(temp)) File.Delete(temp); }
    }
    public string GetScriptInfo(string key) => GetSectionValue("[Script Info]", key);
    public string GetSectionValue(string section, string key)
    {
        var inside = false;
        foreach (var line in Source) { var trim = line.Raw.Trim(); if (trim.StartsWith('[') && trim.EndsWith(']')) inside = trim.Equals(section, StringComparison.OrdinalIgnoreCase); else if (inside && line.Raw.IndexOf(':') is var colon && colon > 0 && line.Raw[..colon].Trim().Equals(key, StringComparison.OrdinalIgnoreCase)) return line.Raw[(colon + 1)..].Trim(); }
        return "";
    }
    internal void SetScriptInfo(string key, string value)
    {
        if (key.IndexOfAny([':', '\r', '\n']) >= 0 || value.IndexOfAny(['\r', '\n']) >= 0) throw new ArgumentException("Invalid Script Info value.");
        var header = Source.FindIndex(l => l.Raw.Trim().Equals("[Script Info]", StringComparison.OrdinalIgnoreCase));
        if (header < 0) { Source.Insert(0, new("[Script Info]", _newline)); header = 0; }
        var index = header + 1;
        for (; index < Source.Count && !Source[index].Raw.TrimStart().StartsWith('['); index++) { var raw = Source[index].Raw; var colon = raw.IndexOf(':'); if (colon > 0 && raw[..colon].Trim().Equals(key, StringComparison.OrdinalIgnoreCase)) { Source[index] = Source[index] with { Raw = raw[..(colon + 1)] + " " + value }; Touch(); return; } }
        Source.Insert(index, new(key + ": " + value, _newline)); Touch();
    }
    internal void Insert(AssRecord record, AssRecord? before = null)
    {
        var index = before is null ? -1 : Source.FindIndex(l => ReferenceEquals(l.Record, before));
        if (index < 0) { var section = record is AssEvent ? "[Events]" : "[V4+ Styles]"; index = Source.FindIndex(l => l.Raw.Trim().Equals(section, StringComparison.OrdinalIgnoreCase)); if (index < 0) { Terminate(); Source.Add(new(section, _newline)); index = Source.Count - 1; } index++; while (index < Source.Count && !Source[index].Raw.TrimStart().StartsWith('[')) index++; }
        if (index > 0 && Source[index - 1].Ending.Length == 0) Source[index - 1] = Source[index - 1] with { Ending = _newline };
        Source.Insert(index, new("", _newline, record)); Synchronize(); Touch();
    }
    private void Terminate() { if (Source.Count > 0 && Source[^1].Ending.Length == 0) Source[^1] = Source[^1] with { Ending = _newline }; }
    internal void Remove(AssRecord record) { Source.RemoveAll(l => ReferenceEquals(l.Record, record)); Synchronize(); Touch(); }
    internal void Swap(AssRecord a, AssRecord b) { var x = Source.FindIndex(l => ReferenceEquals(l.Record, a)); var y = Source.FindIndex(l => ReferenceEquals(l.Record, b)); if (x < 0 || y < 0) return; Source[x] = Source[x] with { Record = b }; Source[y] = Source[y] with { Record = a }; Synchronize(); Touch(); }
    internal void Restore(IReadOnlyList<SourceLine> source) { Source = [.. source]; Synchronize(); Touch(); }
    private void Synchronize()
    {
        var events = Source.Select(l => l.Record).OfType<AssEvent>().ToArray(); var styles = Source.Select(l => l.Record).OfType<AssStyle>().ToArray();
        foreach (var record in _events.Cast<AssRecord>().Concat(_styles)) record.PropertyChanged -= RecordChanged;
        Sync(_events, events); Sync(_styles, styles);
        for (var i = 0; i < events.Length; i++) events[i].Renumber(i + 1);
        foreach (var record in events.Cast<AssRecord>().Concat(styles)) record.PropertyChanged += RecordChanged;
    }
    private static void Sync<T>(ObservableCollection<T> target, T[] items) { for (var i = target.Count - 1; i >= 0; i--) if (!items.Contains(target[i])) target.RemoveAt(i); for (var i = 0; i < items.Length; i++) { if (i < target.Count && EqualityComparer<T>.Default.Equals(target[i], items[i])) continue; var old = target.IndexOf(items[i]); if (old >= 0) target.Move(old, i); else target.Insert(i, items[i]); } }
    private void RecordChanged(object? sender, System.ComponentModel.PropertyChangedEventArgs e) { if (e.PropertyName != "Number") Touch(); }
    internal void Touch() { _cached = null; Revision++; Changed?.Invoke(this, EventArgs.Empty); }
    public AssEvent NewEvent() => new("Dialogue: ", EventFormat, ["0", "0:00:00.00", "0:00:02.00", Styles.FirstOrDefault()?.Name ?? "Default", "", "0", "0", "0", "", ""]);
    public AssStyle NewStyle() => new("Style: ", StyleFormat, ["Default", "Arial", "60", "&H00FFFFFF", "&H0000FFFF", "&H00000000", "&H64000000", "0", "0", "0", "0", "100", "100", "0", "0", "1", "2", "0", "2", "30", "30", "30", "1"]);
}
