using System.Collections.ObjectModel;
using System.ComponentModel;
using System.Runtime.CompilerServices;
using System.Text;

namespace Yoake.Core.Subtitles;

public sealed class AssEvent : INotifyPropertyChanged
{
    private readonly string[] _format;
    private readonly string[] _fields;

    internal AssEvent(int lineIndex, string kind, string[] format, string[] fields)
    {
        LineIndex = lineIndex;
        Kind = kind;
        _format = format;
        _fields = fields;
    }

    public event PropertyChangedEventHandler? PropertyChanged;

    internal int LineIndex { get; set; }
    public string Kind { get; }
    public string Layer { get => Get("Layer", "Marked"); set => Set(value, "Layer", "Marked"); }
    public string Start { get => Get("Start"); set => Set(value, "Start"); }
    public string End { get => Get("End"); set => Set(value, "End"); }
    public string Style { get => Get("Style"); set => Set(value, "Style"); }
    public string Actor { get => Get("Name", "Actor"); set => Set(value, "Name", "Actor"); }
    public string Effect { get => Get("Effect"); set => Set(value, "Effect"); }
    public string Text { get => Get("Text"); set => Set(value, "Text"); }

    public long? StartMilliseconds => AssTime.TryParse(Start, out var value) ? value : null;
    public long? EndMilliseconds => AssTime.TryParse(End, out var value) ? value : null;

    internal string Serialize()
    {
        var serialized = (string[])_fields.Clone();
        var textIndex = FindIndex("Text");
        if (textIndex >= 0)
        {
            serialized[textIndex] = serialized[textIndex]
                .Replace("\r\n", "\\N", StringComparison.Ordinal)
                .Replace("\r", "\\N", StringComparison.Ordinal)
                .Replace("\n", "\\N", StringComparison.Ordinal);
        }
        return $"{Kind}: {string.Join(',', serialized)}";
    }

    private string Get(params string[] names)
    {
        var index = FindIndex(names);
        return index >= 0 ? _fields[index] : string.Empty;
    }

    private void Set(string value, params string[] names)
    {
        var index = FindIndex(names);
        if (index < 0 || string.Equals(_fields[index], value, StringComparison.Ordinal))
            return;
        _fields[index] = value;
        OnPropertyChanged(PropertyNameFor(names[0]));
        if (names[0] is "Start" or "End")
            OnPropertyChanged(names[0] + "Milliseconds");
    }

    private int FindIndex(params string[] names)
    {
        for (var i = 0; i < _format.Length; i++)
        {
            foreach (var name in names)
            {
                if (string.Equals(_format[i], name, StringComparison.OrdinalIgnoreCase))
                    return i;
            }
        }
        return -1;
    }

    private static string PropertyNameFor(string fieldName) => fieldName switch
    {
        "Name" or "Actor" => nameof(Actor),
        "Layer" or "Marked" => nameof(Layer),
        _ => fieldName,
    };

    private void OnPropertyChanged([CallerMemberName] string? propertyName = null)
        => PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(propertyName));
}

public sealed class AssDocument
{
    private readonly List<string> _lines;
    private readonly Encoding _encoding;
    private readonly bool _writeBom;
    private readonly string _newline;

    private AssDocument(List<string> lines, Encoding encoding, bool writeBom, string newline)
    {
        _lines = lines;
        _encoding = encoding;
        _writeBom = writeBom;
        _newline = newline;
        ParseEvents();
    }

    public event EventHandler? Changed;
    public ObservableCollection<AssEvent> Events { get; } = [];

    public static AssDocument CreateEmpty()
    {
        var lines = new List<string>
        {
            "[Script Info]",
            "; Script generated by Yoake",
            "ScriptType: v4.00+",
            "PlayResX: 1920",
            "PlayResY: 1080",
            string.Empty,
            "[V4+ Styles]",
            "Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding",
            "Style: Default,Arial,60,&H00FFFFFF,&H0000FFFF,&H00000000,&H64000000,0,0,0,0,100,100,0,0,1,2,0,2,30,30,30,1",
            string.Empty,
            "[Events]",
            "Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text",
            string.Empty,
        };
        return new AssDocument(lines, new UTF8Encoding(false, true), false, "\r\n");
    }

    public static AssDocument Parse(string text)
    {
        ArgumentNullException.ThrowIfNull(text);
        var newline = DetectNewline(text);
        return new AssDocument(SplitLines(text), new UTF8Encoding(false, true), false, newline);
    }

    public static AssDocument Load(string path)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(path);
        var bytes = File.ReadAllBytes(path);
        var (encoding, bomLength, writeBom) = DetectEncoding(bytes);
        var text = encoding.GetString(bytes, bomLength, bytes.Length - bomLength);
        return new AssDocument(SplitLines(text), encoding, writeBom, DetectNewline(text));
    }

    public string Serialize()
    {
        var lines = _lines.ToArray();
        foreach (var assEvent in Events)
        {
            if ((uint)assEvent.LineIndex < (uint)lines.Length)
                lines[assEvent.LineIndex] = assEvent.Serialize();
        }
        return string.Join(_newline, lines);
    }

    public void Save(string path)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(path);
        var text = Serialize();
        var payload = _encoding.GetBytes(text);
        var preamble = _writeBom ? _encoding.GetPreamble() : [];
        if (preamble.Length == 0)
        {
            File.WriteAllBytes(path, payload);
        }
        else
        {
            var output = new byte[preamble.Length + payload.Length];
            Buffer.BlockCopy(preamble, 0, output, 0, preamble.Length);
            Buffer.BlockCopy(payload, 0, output, preamble.Length, payload.Length);
            File.WriteAllBytes(path, output);
        }

        var serializedLines = SplitLines(text);
        _lines.Clear();
        _lines.AddRange(serializedLines);
    }

    private void ParseEvents()
    {
        Events.Clear();
        var inEvents = false;
        string[]? format = null;

        for (var lineIndex = 0; lineIndex < _lines.Count; lineIndex++)
        {
            var raw = _lines[lineIndex];
            var trimmed = raw.Trim();
            if (trimmed.StartsWith('[') && trimmed.EndsWith(']'))
            {
                inEvents = string.Equals(trimmed, "[Events]", StringComparison.OrdinalIgnoreCase);
                format = null;
                continue;
            }
            if (!inEvents)
                continue;

            if (trimmed.StartsWith("Format:", StringComparison.OrdinalIgnoreCase))
            {
                format = trimmed[7..].Split(',').Select(part => part.Trim()).ToArray();
                continue;
            }

            var colon = raw.IndexOf(':');
            if (colon <= 0 || format is null || format.Length == 0)
                continue;
            var kind = raw[..colon].Trim();
            if (!string.Equals(kind, "Dialogue", StringComparison.OrdinalIgnoreCase) &&
                !string.Equals(kind, "Comment", StringComparison.OrdinalIgnoreCase))
                continue;

            var payload = raw[(colon + 1)..].TrimStart();
            var fields = payload.Split(',', format.Length);
            if (fields.Length < format.Length)
                Array.Resize(ref fields, format.Length);
            for (var i = 0; i < fields.Length; i++)
                fields[i] ??= string.Empty;

            var assEvent = new AssEvent(lineIndex, kind, (string[])format.Clone(), fields);
            assEvent.PropertyChanged += OnEventChanged;
            Events.Add(assEvent);
        }
    }

    private void OnEventChanged(object? sender, PropertyChangedEventArgs e)
        => Changed?.Invoke(this, EventArgs.Empty);

    private static List<string> SplitLines(string text)
        => text.Replace("\r\n", "\n", StringComparison.Ordinal)
            .Replace('\r', '\n')
            .Split('\n')
            .ToList();

    private static string DetectNewline(string text)
        => text.Contains("\r\n", StringComparison.Ordinal) ? "\r\n" : "\n";

    private static (Encoding Encoding, int BomLength, bool WriteBom) DetectEncoding(byte[] bytes)
    {
        if (bytes.AsSpan().StartsWith(Encoding.UTF8.GetPreamble()))
            return (new UTF8Encoding(true, true), 3, true);
        if (bytes.Length >= 2 && bytes[0] == 0xFF && bytes[1] == 0xFE)
            return (new UnicodeEncoding(false, true, true), 2, true);
        if (bytes.Length >= 2 && bytes[0] == 0xFE && bytes[1] == 0xFF)
            return (new UnicodeEncoding(true, true, true), 2, true);

        var utf8 = new UTF8Encoding(false, true);
        try
        {
            _ = utf8.GetString(bytes);
            return (utf8, 0, false);
        }
        catch (DecoderFallbackException exception)
        {
            throw new InvalidDataException("Subtitle file is not UTF-8/UTF-16. Legacy code-page import is not implemented yet; refusing to corrupt the file.", exception);
        }
    }
}

public static class AssTime
{
    public static bool TryParse(string? value, out long milliseconds)
    {
        milliseconds = 0;
        if (string.IsNullOrWhiteSpace(value))
            return false;
        var parts = value.Trim().Split(':');
        if (parts.Length != 3 || !int.TryParse(parts[0], out var hours) || !int.TryParse(parts[1], out var minutes))
            return false;
        var secondsParts = parts[2].Split('.');
        if (secondsParts.Length is < 1 or > 2 || !int.TryParse(secondsParts[0], out var seconds))
            return false;
        var fraction = 0;
        if (secondsParts.Length == 2)
        {
            var digits = secondsParts[1];
            if (digits.Length == 0 || digits.Length > 3 || !int.TryParse(digits, out fraction))
                return false;
            fraction *= digits.Length switch { 1 => 100, 2 => 10, _ => 1 };
        }
        if (hours < 0 || minutes is < 0 or > 59 || seconds is < 0 or > 59)
            return false;
        milliseconds = ((long)hours * 3600 + minutes * 60L + seconds) * 1000 + fraction;
        return true;
    }

    public static string Format(long milliseconds)
    {
        milliseconds = Math.Max(0, milliseconds);
        var hours = milliseconds / 3_600_000;
        milliseconds %= 3_600_000;
        var minutes = milliseconds / 60_000;
        milliseconds %= 60_000;
        var seconds = milliseconds / 1000;
        var centiseconds = (milliseconds % 1000) / 10;
        return $"{hours}:{minutes:00}:{seconds:00}.{centiseconds:00}";
    }
}
