<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsAotCompatible>true</IsAotCompatible>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Avalonia" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Yoake.Core\Yoake.Core.csproj" />
    <ProjectReference Include="..\Yoake.Native\Yoake.Native.csproj" />
  </ItemGroup>
</Project>
