#include "ass/ass_document.h"

#include <QtCore/QRegularExpression>
#include <QtCore/QStringList>

#include <algorithm>

namespace yoake::ass {
namespace {

QStringList splitEventFields(QStringView value)
{
    QStringList fields;
    qsizetype start = 0;
    for (int field = 0; field < 9; ++field) {
        const auto comma = value.indexOf(u',', start);
        if (comma < 0)
            return {};
        fields.push_back(value.mid(start, comma - start).toString().trimmed());
        start = comma + 1;
    }
    fields.push_back(value.mid(start).toString());
    return fields;
}

bool parseInteger(QStringView value, int *result)
{
    bool ok = false;
    const int parsed = value.trimmed().toInt(&ok);
    if (ok)
        *result = parsed;
    return ok;
}

bool parseEventLine(const QString &line, Event *event)
{
    const bool dialogue = line.startsWith(QStringLiteral("Dialogue:"), Qt::CaseInsensitive);
    const bool comment = line.startsWith(QStringLiteral("Comment:"), Qt::CaseInsensitive);
    if (!dialogue && !comment)
        return false;

    const auto colon = line.indexOf(u':');
    const auto fields = splitEventFields(QStringView(line).mid(colon + 1));
    if (fields.size() != 10)
        return false;

    bool startOk = false;
    bool endOk = false;
    Event parsed;
    parsed.comment = comment;
    if (!parseInteger(fields[0], &parsed.layer))
        return false;
    parsed.startMs = parseTime(fields[1], &startOk);
    parsed.endMs = parseTime(fields[2], &endOk);
    parsed.style = fields[3].isEmpty() ? QStringLiteral("Default") : fields[3];
    parsed.actor = fields[4];
    if (!parseInteger(fields[5], &parsed.marginLeft)
        || !parseInteger(fields[6], &parsed.marginRight)
        || !parseInteger(fields[7], &parsed.marginVertical)) {
        return false;
    }
    parsed.effect = fields[8];
    parsed.text = fields[9];
    if (!startOk || !endOk || parsed.endMs < parsed.startMs)
        return false;
    *event = std::move(parsed);
    return true;
}

QString serializeEvent(const Event &event)
{
    const QStringList fields = {
        QString::number(event.layer),
        formatTime(event.startMs),
        formatTime(event.endMs),
        event.style,
        event.actor,
        QStringLiteral("%1").arg(event.marginLeft, 4, 10, QLatin1Char('0')),
        QStringLiteral("%1").arg(event.marginRight, 4, 10, QLatin1Char('0')),
        QStringLiteral("%1").arg(event.marginVertical, 4, 10, QLatin1Char('0')),
        event.effect,
        event.text
    };
    return (event.comment ? QStringLiteral("Comment: ") : QStringLiteral("Dialogue: "))
        + fields.join(u',');
}

} // namespace

Document Document::createDefault()
{
    static const auto defaultScript = QByteArrayLiteral(
        "[Script Info]\n"
        "; Script generated by Yoake\n"
        "ScriptType: v4.00+\n"
        "PlayResX: 1920\n"
        "PlayResY: 1080\n"
        "WrapStyle: 0\n"
        "ScaledBorderAndShadow: yes\n"
        "\n"
        "[V4+ Styles]\n"
        "Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding\n"
        "Style: Default,Arial,64,&H00FFFFFF,&H000000FF,&H00000000,&H80000000,0,0,0,0,100,100,0,0,1,3,1,2,60,60,40,1\n"
        "\n"
        "[Events]\n"
        "Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text\n"
        "Dialogue: 0,0:00:00.00,0:00:05.00,Default,,0000,0000,0000,,\n");
    return parse(defaultScript);
}

Document Document::parse(const QByteArray &contents, QString *error)
{
    Document document;
    QString source = QString::fromUtf8(contents);
    if (!source.isEmpty() && source.front() == QChar::ByteOrderMark)
        source.removeFirst();
    source.replace(QStringLiteral("\r\n"), QStringLiteral("\n"));
    source.replace(u'\r', u'\n');

    const QStringList lines = source.split(u'\n', Qt::KeepEmptyParts);
    bool inEvents = false;
    bool inProjectProperties = false;
    bool sawEvents = false;
    bool sawCanonicalEventFormat = false;
    int lineNumber = 0;
    const QStringList canonicalColumns = {
        QStringLiteral("layer"), QStringLiteral("start"), QStringLiteral("end"),
        QStringLiteral("style"), QStringLiteral("name"), QStringLiteral("marginl"),
        QStringLiteral("marginr"), QStringLiteral("marginv"), QStringLiteral("effect"),
        QStringLiteral("text")
    };
    for (const QString &line : lines) {
        ++lineNumber;
        const QString trimmed = line.trimmed();
        if (trimmed.startsWith(u'[') && trimmed.endsWith(u']')) {
            inEvents = trimmed.compare(QStringLiteral("[Events]"), Qt::CaseInsensitive) == 0;
            inProjectProperties = trimmed.compare(
                QStringLiteral("[Aegisub Project Garbage]"), Qt::CaseInsensitive) == 0;
            sawEvents = sawEvents || inEvents;
        }

        if (inProjectProperties) {
            const qsizetype colon = trimmed.indexOf(u':');
            if (colon > 0) {
                const QString key = trimmed.left(colon).trimmed().toLower();
                const QString value = trimmed.mid(colon + 1).trimmed();
                if (key == QStringLiteral("video file"))
                    document.m_projectProperties.videoFile = value;
                else if (key == QStringLiteral("audio file") || key == QStringLiteral("audio uri"))
                    document.m_projectProperties.audioFile = value;
                else if (key == QStringLiteral("video position")
                    || key == QStringLiteral("aegisub video position"))
                    document.m_projectProperties.videoPosition = std::max(0, value.toInt());
                else if (key == QStringLiteral("active line")
                    || key == QStringLiteral("aegisub active line"))
                    document.m_projectProperties.activeRow = std::max(0, value.toInt());
                else if (key == QStringLiteral("scroll position")
                    || key == QStringLiteral("aegisub scroll position"))
                    document.m_projectProperties.scrollPosition = std::max(0, value.toInt());
            }
        }

        if (inEvents && trimmed.startsWith(QStringLiteral("Format:"), Qt::CaseInsensitive)) {
            QStringList columns;
            const QStringView definition = QStringView(trimmed).mid(trimmed.indexOf(u':') + 1);
            for (const QStringView column : definition.split(u','))
                columns.push_back(column.trimmed().toString().toLower());
            if (columns != canonicalColumns) {
                if (error) {
                    *error = QStringLiteral("Unsupported Events format on line %1; "
                        "Yoake currently writes canonical ASS v4+ events only.").arg(lineNumber);
                }
                return {};
            }
            sawCanonicalEventFormat = true;
        }

        Event event;
        const bool eventRecord = inEvents
            && (trimmed.startsWith(QStringLiteral("Dialogue:"), Qt::CaseInsensitive)
                || trimmed.startsWith(QStringLiteral("Comment:"), Qt::CaseInsensitive));
        if (eventRecord && !sawCanonicalEventFormat) {
            if (error)
                *error = QStringLiteral("Subtitle event appears before its Format declaration on line %1.").arg(lineNumber);
            return {};
        }
        if (eventRecord && !parseEventLine(line, &event)) {
            if (error)
                *error = QStringLiteral("Malformed subtitle event on line %1.").arg(lineNumber);
            return {};
        }
        if (eventRecord) {
            if (document.m_eventOutputRecord < 0)
                document.m_eventOutputRecord = document.m_records.size();
            document.m_events.push_back(event);
            document.m_records.push_back({Record::Kind::Event, {}, event.id});
        } else {
            document.m_records.push_back({Record::Kind::Raw, line, {}});
            if (inEvents && document.m_eventOutputRecord < 0
                && trimmed.startsWith(QStringLiteral("Format:"), Qt::CaseInsensitive)) {
                document.m_eventOutputRecord = document.m_records.size();
            }
        }
    }

    if (!sawEvents || !sawCanonicalEventFormat) {
        if (error) {
            *error = !sawEvents
                ? QStringLiteral("This file has no ASS [Events] section.")
                : QStringLiteral("This ASS file has no supported Events Format declaration.");
        }
        return {};
    }
    if (error)
        error->clear();
    return document;
}

QByteArray Document::serialize() const
{
    QStringList output;
    bool eventsWritten = false;
    for (int index = 0; index <= m_records.size(); ++index) {
        if (!eventsWritten && index == m_eventOutputRecord) {
            for (const Event &event : m_events)
                output.push_back(serializeEvent(event));
            eventsWritten = true;
        }
        if (index == m_records.size())
            break;
        const Record &record = m_records[index];
        if (record.kind == Record::Kind::Raw)
            output.push_back(record.raw);
    }
    if (!eventsWritten) {
        for (const Event &event : m_events)
            output.push_back(serializeEvent(event));
    }
    while (output.size() > 1 && output.back().isEmpty() && output[output.size() - 2].isEmpty())
        output.removeLast();
    return output.join(u'\n').toUtf8();
}

int Document::eventIndex(const QUuid &id) const noexcept
{
    const auto it = std::find_if(m_events.cbegin(), m_events.cend(),
        [&id](const Event &event) { return event.id == id; });
    return it == m_events.cend() ? -1 : static_cast<int>(std::distance(m_events.cbegin(), it));
}

qint64 parseTime(QStringView value, bool *ok)
{
    static const QRegularExpression expression(
        QStringLiteral(R"(^\s*(\d+):([0-5]?\d):([0-5]?\d)(?:[\.:](\d{1,3}))?\s*$)"));
    const auto match = expression.matchView(value);
    if (!match.hasMatch()) {
        if (ok)
            *ok = false;
        return 0;
    }
    const qint64 hours = match.capturedView(1).toLongLong();
    const qint64 minutes = match.capturedView(2).toLongLong();
    const qint64 seconds = match.capturedView(3).toLongLong();
    QString fraction = match.captured(4);
    qint64 milliseconds = 0;
    if (fraction.size() == 1)
        milliseconds = fraction.toLongLong() * 100;
    else if (fraction.size() == 2)
        milliseconds = fraction.toLongLong() * 10;
    else if (fraction.size() == 3)
        milliseconds = fraction.toLongLong();
    if (ok)
        *ok = true;
    return ((hours * 60 + minutes) * 60 + seconds) * 1000 + milliseconds;
}

QString formatTime(qint64 milliseconds)
{
    milliseconds = std::max<qint64>(0, milliseconds);
    const qint64 centiseconds = (milliseconds + 5) / 10;
    const qint64 hours = centiseconds / 360000;
    const qint64 minutes = (centiseconds / 6000) % 60;
    const qint64 seconds = (centiseconds / 100) % 60;
    const qint64 fraction = centiseconds % 100;
    return QStringLiteral("%1:%2:%3.%4")
        .arg(hours)
        .arg(minutes, 2, 10, QLatin1Char('0'))
        .arg(seconds, 2, 10, QLatin1Char('0'))
        .arg(fraction, 2, 10, QLatin1Char('0'));
}

} // namespace yoake::ass
