// <auto-generated />
using Avalonia.Media;

namespace Yoake.UI.Icons;

public static class IconGeometries
{
    public static Geometry Clip => ClipHolder.Value;
    private static class ClipHolder
    {
        internal static readonly Geometry Value = Geometry.Parse("M3 3H10V5H5V10H3ZM14 3H21V10H19V5H14ZM3 14H5V19H10V21H3ZM19 14H21V21H14V19H19Z");
    }
    public static Geometry Close => CloseHolder.Value;
    private static class CloseHolder
    {
        internal static readonly Geometry Value = Geometry.Parse("M5 3L12 10L19 3L21 5L14 12L21 19L19 21L12 14L5 21L3 19L10 12L3 5Z");
    }
    public static Geometry New => NewHolder.Value;
    private static class NewHolder
    {
        internal static readonly Geometry Value = Geometry.Parse("M5 2H15L20 7V22H5ZM7 4V20H18V8H14V4ZM11 10H13V13H16V15H13V18H11V15H8V13H11Z");
    }
    public static Geometry Open => OpenHolder.Value;
    private static class OpenHolder
    {
        internal static readonly Geometry Value = Geometry.Parse("M2 6H10L12 9H22L19 20H3ZM4 8L5 18H17L19.2 11H11L9 8Z");
    }
    public static Geometry Position => PositionHolder.Value;
    private static class PositionHolder
    {
        internal static readonly Geometry Value = Geometry.Parse("M11 2H13V6.1A6 6 0 0 1 17.9 11H22V13H17.9A6 6 0 0 1 13 17.9V22H11V17.9A6 6 0 0 1 6.1 13H2V11H6.1A6 6 0 0 1 11 6.1ZM12 8A4 4 0 1 0 12 16A4 4 0 0 0 12 8Z");
    }
    public static Geometry Redo => RedoHolder.Value;
    private static class RedoHolder
    {
        internal static readonly Geometry Value = Geometry.Parse("M14 5V10H9C5 10 2 13.5 2 19H4C4 15 6 13 9 13H14V17L21 11Z");
    }
    public static Geometry Save => SaveHolder.Value;
    private static class SaveHolder
    {
        internal static readonly Geometry Value = Geometry.Parse("M3 3H18L21 6V21H3ZM5 5V19H19V7L17 5H16V10H7V5ZM9 5V8H14V5ZM7 13H17V18H7Z");
    }
    public static Geometry StepDown => StepDownHolder.Value;
    private static class StepDownHolder
    {
        internal static readonly Geometry Value = Geometry.Parse("M6 10L12 16L18 10L16 8L12 12L8 8Z");
    }
    public static Geometry StepUp => StepUpHolder.Value;
    private static class StepUpHolder
    {
        internal static readonly Geometry Value = Geometry.Parse("M6 14L12 8L18 14L16 16L12 12L8 16Z");
    }
    public static Geometry StyleBottom => StyleBottomHolder.Value;
    private static class StyleBottomHolder
    {
        internal static readonly Geometry Value = Geometry.Parse("M 3.75,18.5625 L 3.75,17.0625 L 11.0625,17.0625 L 3.75,5.4375 L 20.25,5.4375 L 12.9375,17.0625 L 20.25,17.0625 L 20.25,18.5625 L 12,18.5625 L 3.75,18.5625 z");
    }
    public static Geometry StyleDown => StyleDownHolder.Value;
    private static class StyleDownHolder
    {
        internal static readonly Geometry Value = Geometry.Parse("M 3.75,5.4375 L 20.25,5.4375 L 12,18.5625 L 3.75,5.4375 z");
    }
    public static Geometry StyleSort => StyleSortHolder.Value;
    private static class StyleSortHolder
    {
        internal static readonly Geometry Value = Geometry.Parse("M 13.6875,4.875 C 16.6875,5.8125 19.125,8.25 19.125,11.625 C 19.125,14.0625 18,16.3125 16.125,17.625 L 15,15.75 L 12,20.8125 L 18,20.8125 L 17.0625,19.125 C 19.5,17.4375 21,14.8125 21,11.625 C 21,7.875 18.375,4.5 14.4375,3.1875 C 13.125,2.8125 12.5625,4.5 13.6875,4.875 z M 6,3 L 6.9375,4.6875 C 4.5,6.375 3,9 3,12.1875 C 3,15.9375 5.625,19.3125 9.5625,20.625 C 10.875,21 11.4375,19.3125 10.3125,18.9375 C 7.3125,18 4.875,15.5625 4.875,12.1875 C 4.875,9.75 6,7.5 7.875,6.1875 L 9,8.0625 L 12,3 L 6,3 z");
    }
    public static Geometry StyleTop => StyleTopHolder.Value;
    private static class StyleTopHolder
    {
        internal static readonly Geometry Value = Geometry.Parse("M 3.75,5.4375 L 3.75,6.9375 L 11.0625,6.9375 L 3.75,18.5625 L 20.25,18.5625 L 12.9375,6.9375 L 20.25,6.9375 L 20.25,5.4375 L 12,5.4375 L 3.75,5.4375 z");
    }
    public static Geometry StyleUp => StyleUpHolder.Value;
    private static class StyleUpHolder
    {
        internal static readonly Geometry Value = Geometry.Parse("M 3.75,18.5625 L 20.25,18.5625 L 12,5.4375 L 3.75,18.5625 z");
    }
    public static Geometry Theme => ThemeHolder.Value;
    private static class ThemeHolder
    {
        internal static readonly Geometry Value = Geometry.Parse("M12 2A10 10 0 1 0 12 22A8 8 0 0 1 12 2ZM12 4V20A8 8 0 0 0 12 4Z");
    }
    public static Geometry Undo => UndoHolder.Value;
    private static class UndoHolder
    {
        internal static readonly Geometry Value = Geometry.Parse("M10 5L3 11L10 17V13H15C18 13 20 15 20 19H22C22 13.5 19 10 15 10H10Z");
    }
}
