// <auto-generated />
using Avalonia.Media;

namespace Yoake.UI.Icons;

public static class IconGeometries
{
    public static Geometry Clip => ClipHolder.Value;
    private static class ClipHolder
    {
        internal static readonly Geometry Value = Geometry.Parse("M3 3H10V5H5V10H3ZM14 3H21V10H19V5H14ZM3 14H5V19H10V21H3ZM19 14H21V21H14V19H19Z");
    }
    public static Geometry Close => CloseHolder.Value;
    private static class CloseHolder
    {
        internal static readonly Geometry Value = Geometry.Parse("M5 3L12 10L19 3L21 5L14 12L21 19L19 21L12 14L5 21L3 19L10 12L3 5Z");
    }
    public static Geometry New => NewHolder.Value;
    private static class NewHolder
    {
        internal static readonly Geometry Value = Geometry.Parse("M5 2H15L20 7V22H5ZM7 4V20H18V8H14V4ZM11 10H13V13H16V15H13V18H11V15H8V13H11Z");
    }
    public static Geometry Open => OpenHolder.Value;
    private static class OpenHolder
    {
        internal static readonly Geometry Value = Geometry.Parse("M2 6H10L12 9H22L19 20H3ZM4 8L5 18H17L19.2 11H11L9 8Z");
    }
    public static Geometry Position => PositionHolder.Value;
    private static class PositionHolder
    {
        internal static readonly Geometry Value = Geometry.Parse("M11 2H13V6.1A6 6 0 0 1 17.9 11H22V13H17.9A6 6 0 0 1 13 17.9V22H11V17.9A6 6 0 0 1 6.1 13H2V11H6.1A6 6 0 0 1 11 6.1ZM12 8A4 4 0 1 0 12 16A4 4 0 0 0 12 8Z");
    }
    public static Geometry Redo => RedoHolder.Value;
    private static class RedoHolder
    {
        internal static readonly Geometry Value = Geometry.Parse("M14 5V10H9C5 10 2 13.5 2 19H4C4 15 6 13 9 13H14V17L21 11Z");
    }
    public static Geometry Save => SaveHolder.Value;
    private static class SaveHolder
    {
        internal static readonly Geometry Value = Geometry.Parse("M3 3H18L21 6V21H3ZM5 5V19H19V7L17 5H16V10H7V5ZM9 5V8H14V5ZM7 13H17V18H7Z");
    }
    public static Geometry StepDown => StepDownHolder.Value;
    private static class StepDownHolder
    {
        internal static readonly Geometry Value = Geometry.Parse("M6 10L12 16L18 10L16 8L12 12L8 8Z");
    }
    public static Geometry StepUp => StepUpHolder.Value;
    private static class StepUpHolder
    {
        internal static readonly Geometry Value = Geometry.Parse("M6 14L12 8L18 14L16 16L12 12L8 16Z");
    }
    public static Geometry Theme => ThemeHolder.Value;
    private static class ThemeHolder
    {
        internal static readonly Geometry Value = Geometry.Parse("M12 2A10 10 0 1 0 12 22A8 8 0 0 1 12 2ZM12 4V20A8 8 0 0 0 12 4Z");
    }
    public static Geometry Undo => UndoHolder.Value;
    private static class UndoHolder
    {
        internal static readonly Geometry Value = Geometry.Parse("M10 5L3 11L10 17V13H15C18 13 20 15 20 19H22C22 13.5 19 10 15 10H10Z");
    }
}
