#!/usr/bin/env python3
from __future__ import annotations
import argparse
import math
from pathlib import Path
import sys
import xml.etree.ElementTree as ET

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "assets" / "icons" / "functional"
TARGET = ROOT / "src" / "Yoake.UI" / "Icons" / "IconGeometries.g.cs"
NS = "{http://www.w3.org/2000/svg}"

def pascal(name: str) -> str:
    return "".join(part[:1].upper() + part[1:] for part in name.replace("_", "-").split("-") if part)

def generate() -> str:
    entries = []
    for path in sorted(SOURCE.glob("*.svg")):
        root = ET.fromstring(path.read_text(encoding="utf-8"))
        if root.tag != NS + "svg" or root.attrib.get("viewBox") != "0 0 24 24":
            raise SystemExit(f"{path}: functional icons must be SVG with viewBox='0 0 24 24'")
        allowed_tags = {NS + "svg", NS + "path"}
        for node in root.iter():
            if node.tag not in allowed_tags:
                raise SystemExit(f"{path}: unsupported SVG element {node.tag!r}; functional icons currently support <path> only")
            if "transform" in node.attrib:
                raise SystemExit(f"{path}: transforms are not supported by the functional icon generator")
            if node.attrib.get("stroke") not in (None, "none", "currentColor"):
                raise SystemExit(f"{path}: stroke must be theme-aware currentColor")
            if node.attrib.get("fill") not in (None, "none", "currentColor"):
                raise SystemExit(f"{path}: literal/multi-layer fills are not supported; use semantic currentColor")
            if any(name in node.attrib for name in ("clip-rule", "style", "opacity", "fill-opacity", "stroke-opacity", "stroke-dasharray")):
                raise SystemExit(f"{path}: style/fill/clip/opacity semantics are not supported by the functional icon generator")
            if node.attrib.get('fill-rule', 'nonzero') not in ('nonzero', 'evenodd'):
                raise SystemExit(f"{path}: unsupported fill rule")
            if node.attrib.get('stroke-linecap', 'butt') not in ('butt', 'round', 'square') or node.attrib.get('stroke-linejoin', 'miter') not in ('miter', 'round', 'bevel'):
                raise SystemExit(f"{path}: unsupported stroke cap/join")
        paths = [node.attrib.get("d", "").strip() for node in root.iter(NS + "path")]
        if not paths or any(not item for item in paths):
            raise SystemExit(f"{path}: functional icons require non-empty vector paths")
        layers=[]
        for node in root.iter(NS + 'path'):
            raw=('F1 ' if node.attrib.get('fill-rule', 'nonzero')=='nonzero' else 'F0 ')+node.attrib['d'].strip()
            raw=raw.replace('\\','\\\\').replace('"','\\"')
            width=float(node.attrib.get('stroke-width','1')) if node.attrib.get('stroke')=='currentColor' else 0
            if not math.isfinite(width) or width<0: raise SystemExit(f'{path}: invalid stroke width')
            cap={'butt':'Flat','round':'Round','square':'Square'}[node.attrib.get('stroke-linecap','butt')]
            join=node.attrib.get('stroke-linejoin','miter').capitalize()
            fill='false' if node.attrib.get('fill')=='none' else 'true'
            layers.append(f'("{raw}", {fill}, {width:g}, PenLineCap.{cap}, PenLineJoin.{join})')
        entries.append((pascal(path.stem), ', '.join(layers)))

    lines = [
        "// <auto-generated />",
        "using Avalonia.Media;",
        "",
        "namespace Yoake.UI.Icons;",
        "",
        "public static class IconGeometries",
        "{",
        "    // Widen strokes once into recolorable PathIcon geometry. SVG caps,",
        "    // joins and fill rules survive normalization; no bitmap wrappers.",
        "    private static Geometry Build(params (string Path, bool Fill, double Stroke, PenLineCap Cap, PenLineJoin Join)[] layers)",
        "    {",
        "        Geometry? result = null;",
        "        void Add(Geometry part) => result = result is null ? part : new CombinedGeometry(GeometryCombineMode.Union, result, part);",
        "        foreach (var layer in layers)",
        "        {",
        "            var path = Geometry.Parse(layer.Path);",
        "            if (layer.Fill) Add(path);",
        "            if (layer.Stroke > 0) Add(path.GetWidenedGeometry(new Pen(Brushes.White, layer.Stroke, lineCap: layer.Cap, lineJoin: layer.Join)));",
        "        }",
        "        return result ?? new StreamGeometry();",
        "    }",
    ]
    for name, data in entries:
        lines.append(f"    public static Geometry {name} => {name}Holder.Value;")
        lines.append(f"    private static class {name}Holder")
        lines.append("    {")
        lines.append(f'        internal static readonly Geometry Value = Build({data});')
        lines.append("    }")
    lines += ["}", ""]
    return "\n".join(lines)

def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    generated = generate()
    if args.check:
        if not TARGET.exists() or TARGET.read_text(encoding="utf-8") != generated:
            print(f"{TARGET} is stale; run tools/generate-icons.py", file=sys.stderr)
            return 1
        return 0
    TARGET.parent.mkdir(parents=True, exist_ok=True)
    TARGET.write_text(generated, encoding="utf-8", newline="\n")
    return 0

if __name__ == "__main__":
    raise SystemExit(main())
