#!/usr/bin/env python3
from __future__ import annotations
import argparse
from pathlib import Path
import sys
import xml.etree.ElementTree as ET

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "assets" / "icons" / "functional"
TARGET = ROOT / "src" / "Yoake.UI" / "Icons" / "IconGeometries.g.cs"
NS = "{http://www.w3.org/2000/svg}"

def pascal(name: str) -> str:
    return "".join(part[:1].upper() + part[1:] for part in name.replace("_", "-").split("-") if part)

def generate() -> str:
    entries = []
    for path in sorted(SOURCE.glob("*.svg")):
        root = ET.fromstring(path.read_text(encoding="utf-8"))
        if root.tag != NS + "svg" or root.attrib.get("viewBox") != "0 0 24 24":
            raise SystemExit(f"{path}: functional icons must be SVG with viewBox='0 0 24 24'")
        allowed_tags = {NS + "svg", NS + "path"}
        for node in root.iter():
            if node.tag not in allowed_tags:
                raise SystemExit(f"{path}: unsupported SVG element {node.tag!r}; functional icons currently support <path> only")
            if "transform" in node.attrib:
                raise SystemExit(f"{path}: transforms are not supported by the functional icon generator")
            if node.attrib.get("stroke") not in (None, "none"):
                raise SystemExit(f"{path}: strokes are not supported by the functional icon generator")
            if node.attrib.get("fill") not in (None, "currentColor"):
                raise SystemExit(f"{path}: literal/multi-layer fills are not supported; use semantic currentColor")
            if any(name in node.attrib for name in ("fill-rule", "clip-rule", "style", "opacity", "fill-opacity", "stroke-opacity")):
                raise SystemExit(f"{path}: style/fill/clip/opacity semantics are not supported by the functional icon generator")
        paths = [node.attrib.get("d", "").strip() for node in root.iter(NS + "path")]
        if not paths or any(not item for item in paths):
            raise SystemExit(f"{path}: functional icons require non-empty vector paths")
        raw = " ".join(paths).replace("\\", "\\\\").replace('"', '\\"')
        entries.append((pascal(path.stem), raw))

    lines = [
        "// <auto-generated />",
        "using Avalonia.Media;",
        "",
        "namespace Yoake.UI.Icons;",
        "",
        "public static class IconGeometries",
        "{",
    ]
    for name, data in entries:
        lines.append(f"    public static Geometry {name} => {name}Holder.Value;")
        lines.append(f"    private static class {name}Holder")
        lines.append("    {")
        lines.append(f'        internal static readonly Geometry Value = Geometry.Parse("{data}");')
        lines.append("    }")
    lines += ["}", ""]
    return "\n".join(lines)

def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    generated = generate()
    if args.check:
        if not TARGET.exists() or TARGET.read_text(encoding="utf-8") != generated:
            print(f"{TARGET} is stale; run tools/generate-icons.py", file=sys.stderr)
            return 1
        return 0
    TARGET.parent.mkdir(parents=True, exist_ok=True)
    TARGET.write_text(generated, encoding="utf-8", newline="\n")
    return 0

if __name__ == "__main__":
    raise SystemExit(main())
